package protocol.request;

public interface RequisitionOperations {
    String LOGIN = "LOGIN";
    String LOGOUT = "LOGOUT";
    String ADMIN_BUSCAR_USUARIOS = "ADMIN_BUSCAR_USUARIOS";
    String ADMIN_BUSCAR_USUARIO = "ADMIN_BUSCAR_USUARIO";
    String ADMIN_CADASTRAR_USUARIO = "ADMIN_CADASTRAR_USUARIO";
    String ADMIN_ATUALIZAR_USUARIO = "ADMIN_ATUALIZAR_USUARIO";
    String ADMIN_DELETAR_USUARIO = "ADMIN_DELETAR_USUARIO";
    String CADASTRAR_USUARIO = "CADASTRAR_USUARIO";
}
